export { mediaRegistry, DEFAULT_SOURCE_CONFIG } from './registry'
export type { MediaSource, MediaAsset, SearchOptions, MediaSourceConfig } from './registry'
export { UnsplashSource } from './sources/unsplash'
export { PexelsSource } from './sources/pexels'
export { PixabaySource } from './sources/pixabay'
export { ScreenCaptureSource } from './sources/screen-capture'
export { analyzeEpisodeMedia, searchMediaForNeed } from './analysis'
export type { MediaNeed, MediaAnalysisResult } from './analysis'
export { generateBlocks, assembleIndexHtml } from './block-gen'
export type { GeneratedBlock, GenerationResult } from './block-gen'
export { runQualityGate } from './quality'
export type { QualityGateReport, QualityCheck } from './quality'
export { queueManager } from './queue'
